Issue #2 fix
ijsto/strapi-provider-email-mailjet pull request #3
Opened 2020-11-16 16:16 UTC by burlakko

2020-11-17 22:47 UTC, ScottAgirs requested changes
Minor patches and we're good to go!

Thanks a bunch for the PR!

PS. if need any help, feel free to reach out!

2020-11-17 22:47 UTC, ScottAgirs commented on lib/index.js
> +const normalizeTo = to => {
Please rename `to` to `recipients`

2020-11-17 22:47 UTC, ScottAgirs commented on lib/index.js
> +   to.map(i =>
Please rename `i` to `recipient`

2020-11-17 22:47 UTC, ScottAgirs commented on lib/index.js
> +        },
Looks like we're currently not passing in the `toName` and `settings` to `normalizeTo()` - could you please add and ensure it works? :)

2020-11-17 22:47 UTC, ScottAgirs commented on lib/index.js
> +                To: normalizeTo(to),
Think we might want to pass in the `toName` and `settings` here

2020-11-18 08:55 UTC, burlakko commented
All valid points. But while implementing I found the `normalizeTo` function looks inconsistent, e.g. `recipients` params may be an array or a string, settings.defaultTo and `recipientName` (`toName`) - only a string.
Also I've found out that the plugin's API is different from the native one. Native API has only `to` and `settings.defaultTo` params which may be just an email address string, an `{Email: ..., Name: ...}` object or an array of strings or objects. This actually looks very flexible and simple. Maybe we should stick with this approach here? What do you think?

2020-11-20 15:44 UTC, ScottAgirs commented
@burlakko sadly, deprecating `defaultToName` and/or `toName` is not an option, please consider adding extra handler to ensure capability. If nothing comes to mind, lmk if nothing comes to mind, I'll tackle this over the next few days.

2020-11-21 22:04 UTC, ScottAgirs commented
@burlakko thanks again for your input, this should be addressed with [Release 3.3.0](https://github.com/ijsto/strapi-provider-email-mailjet/releases/tag/3.3.0)

2020-11-21 22:04 UTC, closed without merging

2020-11-22 12:34 UTC, burlakko commented
Oh I actually planned to deal with it on monday, but you already got it done. Thanx!

2020-11-22 12:44 UTC, burlakko commented
Though I see a potential problem here.

Line 37: `To = [{ Email: to, Name: toName || settings.defaultToName }];` will stick the `defaultToName` even if you're using the different `to`.

Consider following example
```
...
  settings: {
      defaultTo: "john.doe@ijs.to",
      defaultToName: "Johnny Bravodoe",
    }
...
strapi.plugins["email"].services.email.send({to: 'hanna@whatever.email', ...})
```
It will result into `[{ Email: 'hanna@whatever.email', Name: 'Johnny Bravodoe' }]` recipient, which is obviously not what expected.