Default to name fix
ijsto/strapi-provider-email-mailjet pull request #5
Opened 2020-11-22 18:52 UTC by burlakko

Fixes problem of potential mismatch of receiver's email address and name as described [here](https://github.com/ijsto/strapi-provider-email-mailjet/pull/3#issuecomment-731742512).
Also adds support of email only arrays (`['email1@..., email2@...]`) and enables throwing 'empty to' error only if both `to` and `defaultTo` are not set.

2020-11-27 20:17 UTC, ScottAgirs requested changes
One small tweak, otherwise LGTM.

Please adjust and make sure you test as well.

Thanks Danny for the PR!

2020-11-27 20:17 UTC, ScottAgirs commented on lib/index.js
> +                to: normalizeReceiver(to, toName, settings.defaultTo, settings.defaultToName),
Please adjust - `to` keyword must be capitalized here, so `To`.

2020-11-27 22:21 UTC, ScottAgirs approved these changes
LGTM.

You can expect this to be merged in the following days.
Thank you @burlakko for the PR!

2020-11-30 11:42 UTC, burlakko commented
@ScottAgirs fixed and tested.

But one more bug seems to be found. If you'll add `Cc`(as well `Bcc` and `Attachments`) field to your message, you'll get `msg` object of following structure:
```
{
  Messages: [
    {
      From: ...
      To: ...
      ...
    }
  ],
  Cc: ...,
  Bcc: ...
}
```

2020-12-23 18:04 UTC, ScottAgirs commented
Hey @burlakko thanks for the commits and sorry for the delay, I think we're good to merge, the last thing, though - it looks like your ESLint/Prettier settings are reformatting things - please revert those changes, then merging in! :)

2021-01-18 09:46 UTC, burlakko commented
Hi @ScottAgirs! Sorry for the delay. Can you please provide your eslint config file, so i could apply desired code formatting? Also maybe it's a good idea to have it inside of project?

2021-01-18 22:53 UTC, ScottAgirs approved these changes
LGTM

2021-01-18 22:57 UTC, merged

2021-01-18 22:58 UTC, ScottAgirs commented
@burlakko thanks for the PR, and you make a good point. I think the Linting issue is ok for now, we will be adding linting config to the project as you suggested! :) 

Cheers!